version: "3.9"

services:
  workspace:
    build:
      context: .
      dockerfile: ./workspace/Dockerfile
      args:
        - TARGET_PYTHON_VERSION=${PYTHON_VERSION:-3.9}
    volumes:
      - ${APP_CODE_PATH_HOST:-../}:${APP_CODE_PATH_CONTAINER:-/usr/src/app}
